--Q1. What is the total revenue generated by male v/s female customers
SELECT
	gender,
	SUM(purchase_amount) AS TOTAL_REVENUE_GENERATED
FROM Customer_Info
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT
	customer_id,
	purchase_amount
FROM Customer_Info
WHERE discount_applied = 'Yes' AND purchase_amount >(SELECT AVG(purchase_amount) FROM Customer_Info)


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT *
FROM(
	SELECT
		item_purchased,
		ROUND(AVG(review_rating),2) AS PRODUCT_AVG_RATING,
		RANK() OVER (ORDER BY ROUND(AVG(review_rating),2) DESC) AS PRODUCTS_RANK
	FROM Customer_Info
	GROUP BY item_purchased
)t
WHERE PRODUCTS_RANK <=5

--Q4 Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT 
	shipping_type,
	ROUND(AVG(CAST(purchase_amount AS FLOAT)), 2) AS AVG_PURCHASE_AMOUNT
FROM Customer_Info
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
SELECT 
	subscription_status,
	COUNT(customer_id) AS TOATL_NR_OF_CUSTOMERS,
	ROUND(AVG(CAST(purchase_amount AS FLOAT)),2) AS AVERAGE_AMOUNT,
	SUM(purchase_amount) AS TOTAL_REVENUE
FROM Customer_Info
GROUP BY subscription_status
ORDER BY TOTAL_REVENUE, AVERAGE_AMOUNT

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
	item_purchased,
	CONCAT(100 * SUM(CASE WHEN discount_applied = 'YES' THEN 1 ELSE 0 END) / COUNT(*), '%') AS DISCOUNT_RATE
FROM Customer_Info
GROUP BY item_purchased
ORDER BY DISCOUNT_RATE DESC

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
SELECT 
	CUSTOMER_SEGMENTATION,
	COUNT(*) AS TOTAL_NR_OF_CUSTOMERS
FROM(
	SELECT
		customer_id,
		previous_purchases,
		CASE
			WHEN previous_purchases = 1 THEN 'NEW CUSTOMER'
			WHEN previous_purchases BETWEEN 2 AND 10 THEN 'RETURNING CUSTOMER'
			ELSE 'LOYAL CUSTOMER'
		END AS CUSTOMER_SEGMENTATION
	FROM Customer_Info
)t
GROUP BY CUSTOMER_SEGMENTATION

--Q8. What are the top 3 most purchased products within each category?
SELECT 
	*
FROM(
	SELECT
		item_purchased,
		category,
		COUNT(*) NUMBER_OF_PURCHASED_PRODUCTS,
		ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY COUNT(*) DESC) AS PRODUCTS_RANK
	FROM Customer_Info
	GROUP BY item_purchased, category
)t
WHERE PRODUCTS_RANK <=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
	subscription_status,
	COUNT(customer_id) AS REPEATED_CUSTOMERS
FROM Customer_Info
WHERE previous_purchases > 5
GROUP BY subscription_status

--Q10. What is the revenue contribution of each age group? 
SELECT 
	age_group,
	SUM(purchase_amount) AS TOTAL_REVENUE
FROM Customer_Info
GROUP BY age_group
ORDER BY TOTAL_REVENUE DESC

SELECT  *
FROM Customer_Info